### ISSUE TITLE
Counterfile seems to be ignored

### ISSUE THREAD

**Issue by kyflores** [RadeonOpenCompute/ROCm-Profiler#3]
Hi,

I'm having a bit of trouble with passing in a counterfile for rocm-profiler, as the profiler output suggests that it didn't acknowledge a list file. I have rocm-profiler generate the counterlist as detailed in the previous issue, where it outputs `counters_HSA_Graphics_IP_v8.txt` into the local directory. I edited that file to only contain Wavefonts, VALUinsts and SALUinsts.

I have just compiled the saxpy example, and I then run:
`rocm-profiler --hsapmc --counterfile counters_HSA_Graphics_IP_v8.txt prj0 ` 
where prj0 is the executable's name. The output is:
```
CodeXL GPU Profiler V4.0.6036 is enabled
No counter file specified. Only counters that will fit into a single pass will be enabled.
0 errors
Session output path: /home/kyle/Session1.csv
```
The output file, Session1.csv has relevant profiling information but it has all the default selections, not limited to what's in the counterfile. The profiler version is V4.0.6036, and the installation is on Ubuntu 16.04 with rocm 1.4 all installed from repositories. 

Am I making a very basic mistake in the usage? Thanks for having a look at this.

**Comment by chesik-amd** [comment]
Hi kyflores,

Yes, this was broken, but it has been fixed.

https://github.com/GPUOpen-Tools/CodeXL/commit/6e9529175298e77e034ab9dfd4e3b77e882ccdba

You can rebuild the profiler from the CodeXL repository.  To build just the rocm-profiler use:

bash backend_build.sh skip-32bitbuild skip-oclprofiler.

You would then want to replace CodeXLGpuProfiler in /opt/rocm/profiler/bin with the version you built.  This fix will be included in the next release of the rocm profiler

**Comment by kyflores** [comment]
Hi,

Thanks for your response and solution. It worked great for my needs right now!
